# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pr:
- master

pool: Azure-VSTS-VS2017

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzurePowerShell@3
  displayName: 'Validate ARM Templates'
  inputs:
    azureSubscription: 'Reform-CFT-VH-Dev'
    ScriptType: InlineScript
    Inline: |
      $armTemplateFolders = Get-ChildItem -Path $(Build.SourcesDirectory)\vh-arm-templates\* -Directory
        
      foreach ($folder in $armTemplateFolders){
      Write-Output ("Validating templae {0}" -f $folder.Name)
      Test-AzureRmResourceGroupDeployment -ResourceGroupName vh-arm-templates -Mode Incremental -TemplateFile (($folder | Resolve-Path -Relative) + '\' + '*.json') -TemplateParameterFile (($folder | Resolve-Path -Relative) + '\' + '*.parameters.json') -Verbose      }
    azurePowerShellVersion: LatestVersion



